### ISSUE TITLE
wrong version of pip used

### ISSUE THREAD

**Issue by arvieyaar** [lowerquality/gentle#129]
When running the installer I got the following

> Searching for pip
> Best match: pip 9.0.1
> Adding pip 9.0.1 to easy-install.pth file
> Installing pip script to /Library/Frameworks/Python.framework/Versions/3.5/bin
> Installing pip3 script to /Library/Frameworks/Python.framework/Versions/3.5/bin
> Installing pip3.5 script to /Library/Frameworks/Python.framework/Versions/3.5/bin
> 
> Using /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
> Processing dependencies for pip
> Finished processing dependencies for pip
> The directory '/Users/Yaar/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/Users/Yaar/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Processing /Users/Yaar/PycharmProjects/gentle
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/tmp/pip-cesj5vbl-build/setup.py", line 2, in <module>
>         from gentle import __version__
>       File "/private/tmp/pip-cesj5vbl-build/gentle/__init__.py", line 1, in <module>
>         from __version__ import __version__
>     ImportError: No module named '__version__'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-cesj5vbl-build/

This was solved using changing 

> sudo pip install 

. to 

> sudo pip2 install .

in install_deps.sh

**Comment by strob** [comment]
what operating system are you using?

**Comment by arvieyaar** [comment]
Sorry should have mentioned that, Mac 10.11.6

**Comment by strob** [comment]
Did you install python3 in an unusual way? AFAICT, homebrew and
easy_install still give python/pip to version2.

**Comment by arvieyaar** [comment]
Ah,  I'm pretty sure I messed with my pip version in order to install python 3 and tensorflow which would explain why it defaulted to 3.
