### ISSUE TITLE
Error running the CLI command the first time, works the second time

### ISSUE THREAD

**Issue by dhuv** [lowerquality/gentle#195]
I compiled Gentle on Debian Linux. When I run the command to align text, it sometimes throws the error below. Running the exact command right after runs properly.

Errors the first time
-------------------------------------------------------------------------------------
INFO:root:converting audio to 8K sampled wav
INFO:root:starting alignment
Traceback (most recent call last):
  File "/home/dhuv/git/gentle/align.py", line 55, in <module>
    result = aligner.transcribe(wavfile, progress_cb=on_progress, logging=logging)
  File "/home/dhuv/git/gentle/gentle/forced_aligner.py", line 23, in transcribe
    words, duration = self.mtt.transcribe(wavfile, progress_cb=progress_cb)
  File "/home/dhuv/git/gentle/gentle/transcriber.py", line 51, in transcribe
    pool.map(transcribe_chunk, range(n_chunks))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/dhuv/git/gentle/gentle/transcriber.py", line 38, in transcribe_chunk
    k.push_chunk(buf)
  File "/home/dhuv/git/gentle/gentle/standard_kaldi.py", line 37, in push_chunk
    self._p.stdin.write(buf) #arr.tostring())
BrokenPipeError: [Errno 32] Broken pipe
-------------------------------------------------------------------------------------

Runs properly the second time
-------------------------------------------------------------------------------------
INFO:root:converting audio to 8K sampled wav
INFO:root:starting alignment
INFO:root:1/32
INFO:root:2/32
INFO:root:3/32
INFO:root:4/32
INFO:root:5/32
INFO:root:6/32
INFO:root:7/32
INFO:root:8/32
INFO:root:9/32
INFO:root:10/32
INFO:root:11/32
INFO:root:12/32
INFO:root:13/32
INFO:root:14/32
INFO:root:15/32
INFO:root:16/32
INFO:root:17/32
INFO:root:18/32
INFO:root:19/32
INFO:root:20/32
INFO:root:21/32
INFO:root:22/32
INFO:root:23/32
INFO:root:24/32
INFO:root:25/32
INFO:root:26/32
INFO:root:27/32
INFO:root:28/32
INFO:root:29/32
INFO:root:30/32
INFO:root:31/32
INFO:root:32/32
INFO:root:118 unaligned words (of 2056)
INFO:root:after 2nd pass: 71 unaligned words (of 2056)
-------------------------------------------------------------------------------------

**Comment by ensomniac** [comment]
I know this is an old comment, but I ran into the same/similar issue on Centos7. It seems that setting the thread count to 1 runs without fail every time. Setting it to 2 starts this intermittent instability. The more threads I use the more consistently it will fail. At 8 threads I consistently get '[Errno 32] Broken pipe'.
