### ISSUE TITLE
Install in windows OS

### ISSUE THREAD

**Issue by zf223669** [lowerquality/gentle#298]
I download the code and install in windows OS with MiniAnaconda，however， when i run the server,it showed a error like below:
Traceback (most recent call last):
  File "waitress_server.py", line 2, in <module>
    import app
  File "D:\GestureSynthesisProjects\SGToolkit\SGToolkit-main\app.py", line 4, in <module>
    import sg_core_api as sgapi
  File "D:\GestureSynthesisProjects\SGToolkit\SGToolkit-main\sg_core_api.py", line 29, in <module>
    from sg_core.scripts.gesture_generator import GestureGenerator
  File "D:\GestureSynthesisProjects\SGToolkit\SGToolkit-main\sg_core\scripts\gesture_generator.py", line 22, in <module>
    gentle_resources = gentle.Resources()
  File "D:\GestureSynthesisProjects\gentle\gentle\resources.py", line 19, in __init__
    require_dir(self.proto_langdir)
  File "D:\GestureSynthesisProjects\gentle\gentle\resources.py", line 16, in require_dir
    raise RuntimeError("No resource directory %s.  Check %s environment variable?" % (path, ENV_VAR))

How could I fixed it?

**Comment by zxul767** [comment]
I don't think there's official support for Windows, but you may want to try what's suggested in https://github.com/lowerquality/gentle/issues/322
