### ISSUE TITLE
Installation Fails: Missing 'zope-interface' and RuntimeError for GENTLE_RESOURCES_ROOT

### ISSUE THREAD

**Issue by janksmap** [lowerquality/gentle#339]
When following these instructions:
```
git clone https://github.com/lowerquality/gentle.git
cd gentle
./install.sh
```
everything downloads fine until the very end when I get this error:

`error: The 'zope-interface>=5' distribution was not found and is required by twisted`

When I run the following command, it breaks.
`python3 align.py audio.mp3 words.txt`

```
Traceback (most recent call last):
  File "<user>/gentle/align.py", line 49, in <module>
    resources = gentle.Resources()
  File "<user>/gentle/gentle/resources.py", line 19, in __init__
    require_dir(self.proto_langdir)
  File "<user>/gentle/gentle/resources.py", line 16, in require_dir
    raise RuntimeError("No resource directory %s.  Check %s environment variable?" % (path, ENV_VAR))
RuntimeError: No resource directory <user>/gentle/exp.  Check GENTLE_RESOURCES_ROOT environment variable?
```

**Comment by bd0ug** [comment]
Same issue here

**Comment by 00siddhant00** [comment]
U can still run it using docker... if ur not familiar with it, its not really that hard, just few click away, below are the instructions:

### Installation Steps for Running Gentle via Docker Desktop
### Follow these steps to set up and run Gentle using Docker Desktop:

### Step 1: Install Docker Desktop
- Download and install Docker Desktop from the official Docker website: [Docker Desktop](https://www.docker.com).
- Launch Docker Desktop and ensure it's running properly.

### Step 2: Search for the Gentle Docker Image
- Open Docker Desktop.
- Open Image section.
- In the search bar, type `lowerquality/gentle`.
- Select the image from the search results and click Pull to download the image.

### Step 3: Configure Advanced Settings
- After the image is pulled, navigate to Advanced Settings in Docker Desktop.
- Give a related name to container if u want.
- Set the host port to 8765. This ensures the server will listen on [http://localhost:8765](http://localhost:8765).

### Step 4: Run the Docker Container
- Start the container using the downloaded image.
- Docker Desktop will automatically start the server and map the required ports.

### Step 5: Access the Gentle Interface
- Open any web browser and navigate to [http://localhost:8765](http://localhost:8765).

You should see the graphical interface for Gentle. You can now transcribe audio, view results, or download data.

**Comment by LittleTerry** [comment]
same here

**Comment by quocvu** [comment]
same issue.  
and my provider doesn't allow running a container with such old python version
